# Generated by Django 2.2b1 on 2022-06-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='context',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='massage',
            name='room',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=100),
        ),
    ]
